### PR TITLE
I2B2UI-439: Removed modifier duplication in synonym terms (in browse & search)

### PR DESCRIPTION
**Pull request by hackerceo**

### CODE REVIEW

**Comment by marcdanie** [comment]
Unfortunately, I am still seeing the modifier duplication for synonym terms.

**Comment by hackerceo** [comment]
I found and fixed a second bug that was present and responsible for allowing non-first synonyms to remain in an "unloaded" state which allowed the user to repeatedly fire its loading event

**Comment by marcdanie** [comment]
I am not longer seeing any duplicate modifiers when browsing modifiers. However, I am not able to see any modifiers if I select "Show Modifier" for any term in the ontology search results

**Comment by hackerceo** [comment]
This has been fixed now

**Comment by marcdanie** [comment]
I am able to "Show Modifiers" for some terms in the search treeview but I get the following error for some terms
`Uncaught TypeError: Cannot read properties of undefined (reading 'forEach')
    at getAllChildren (ONT_view_Search.js:148:33)
    at ONT_view_Search.js:160:13
    at scopedCallback.callback (ONT_sdx_CONCPT.js:481:9)
    at retCommObj._defaultCallbackOK (i2b2_cell_communicator.js:325:35)
    at Object.success (i2b2_cell_communicator.js:224:34)
    at c (jquery.min.js:2:28327)
    at Object.fireWith [as resolveWith] (jquery.min.js:2:29072)
    at l (jquery.min.js:2:79901)
    at XMLHttpRequest.<anonymous> (jquery.min.js:2:82355)`

**Comment by hackerceo** [comment]
This last commit should fix the bug that you found

**Review by marcdanie — APPROVED** [review]

**Pull request merged**
