### PR TITLE
I2B2UI-591: Show term in treeview from Query Tool

### PR DESCRIPTION
**Pull request by hackerceo**

### CODE REVIEW

**Comment by marcdanie** [comment]
I am noticing an issue here. When I click View in Tree from the query tool, it looks like all the concepts at the same level as the selected term are duplicated if it is not a root node. If it is a root node such as **Diagnoses** then the term is not in bold and the node is also expanded.

**Comment by hackerceo** [comment]
This issue has been resolve.  Awaiting your review.

**Comment by marcdanie** [comment]
The duplicate node issue has been resolved. However, I am still noticing if it is a root node such as Diagnoses then the root term is not in bold and the node is also expanded.

 Also nothing appears to happen when **view in tree** is selected for a modifier in the query tool. What is the expected behavior in that case?

**Comment by hackerceo** [comment]
Fixed the root node issue, good catch.  Modifiers are going to be handled as an enhancement ticket per previous scrum discussions.

**Review by marcdanie — APPROVED** [review]

**Pull request merged**
