### PR TITLE
I2B2UI-495: D3-based breakdown graphs are now displaying

### PR DESCRIPTION
**Pull request by hackerceo**

### CODE REVIEW

**Comment by marcdanie** [comment]
Looks good. However, I am not seeing obfuscated breakdown graphs and tables if I log in as an obfuscated user (demo_obf).

**Comment by hackerceo** [comment]
Thanks, I fixed this issue now.

**Comment by marcdanie** [comment]
I am seeing obfuscated values now. One other issue I noticed is that the Demographic Distribution section is displayed when I run a query without breakdowns

**Comment by hackerceo** [comment]
Doesn't this also occur in pre-refactor code? It is built into the
templates. The templates were not changed.

**Pull request merged**
